# Generated by Django 4.2 on 2023-04-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อผู้ถาม')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อปัญหา')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='รายละเอียดปัญหา')),
                ('email', models.CharField(max_length=200, verbose_name='อีเมล์ผู้ติดต่อ')),
                ('done', models.BooleanField(default=False, verbose_name='แก้ปัญหาจบหรือยัง')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='สรุปปัญหานี้แก้อย่างไร')),
            ],
        ),
    ]
